# -*- coding: utf-8 -*-
"""predictFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ExyvS4PdebWMpOE2hR6ScmC4PXPMMKd
"""

from google.colab import drive
drive.mount('/content/gdrive')

import tensorflow as tf 
model = tf.keras.models.load_model('gdrive/My Drive/train_model.h5')

!pip install konlpy

from konlpy.tag import Okt
okt = Okt()

def tokenize(doc):
    # norm은 정규화, stem은 근어로 표시하기를 나타냄
    return ['/'.join(t) for t in okt.pos(doc, norm=True, stem=True)]

import pickle
with open('gdrive/My Drive/text.pickle', 'rb') as handle:
    text = pickle.load(handle)

selected_words = [f[0] for f in text.vocab().most_common(500)]

print(selected_words[:50])

def term_frequency(doc):
    return [doc.count(word) for word in selected_words]

import numpy as np

def predict_pos_neg(review):
    token = tokenize(review)
    tf = term_frequency(token)
    data = np.expand_dims(np.asarray(tf).astype('float32'), axis=0)
    score = float(model.predict(data))
    if(score > 0.5):
        print("[{}]는 {:.2f}% 확률로 긍정 리뷰이지 않을까 추측해봅니다.^^\n".format(review, score * 100))
    else:
        print("[{}]는 {:.2f}% 확률로 부정 리뷰이지 않을까 추측해봅니다.^^;\n".format(review, (1 - score) * 100))